---
#
# Ansible managed
#
repository:
  description: Install and configure revealmd on your system.
  homepage: https://robertdebock.nl/
  topics: revealmd, presentation, html, markdown, nodejs, git, npm, slides, development, ansible, molecule, playbook
